---
title: "Code1"
output: pdf_document
date: "2023-12-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Setting Working Directory and Loading Dataset
```{r}
setwd("C:\\Users\\joewe\\Desktop\\LAU\\Semesters\\Fall 2023\\CSC463\\Projects\\CSC463\\Phase3")
dataset <- read.csv("ky_louisville_2023_01_26.csv")
```

Importing Libraries
```{r}
library(caret)
library(rpart)
library(rpart.plot)
library(randomForest)
library(ipred)
library(gbm)
```

Data Preprocessing
```{r}
# Removing rows that contain missing values
dataset <- na.omit(dataset)
print(nrow(dataset)) # We now have 3585 rows with no missing values

# Removing duplicate rows if there are any.
dataset <- unique(dataset)
print(nrow(dataset)) # No duplicate rows, we still have 3585

# Identifying and removing variables with only one level
dataset <- dataset[, sapply(dataset, function(x) length(unique(x)) > 1)]

# Encoding 'male' and 'female' in subject_sex to numerical values (male: 0, female: 1)
dataset$subject_sex <- as.numeric(dataset$subject_sex == "female")
```

Data Splitting
```{r}
set.seed(126)
split_index <- sample(1:nrow(dataset), 0.8 * nrow(dataset), replace=F)
train_data <- train_data[split_index, ]
test_data <- test_data[-split_index, ]
```

Bagging
```{r}
dataset <- na.omit(dataset)

# Create a Random Forest model
ba_model <- randomForest(subject_sex ~ ., data = train_data, mtry = (ncol(train_data) -1), importance = T, ntree = 1000)

# Print a summary of the model
print(ba_model)
```

```{r}
# Make predictions on the test data
predictions <- predict(ba_model, newdata = test_data)

# Evaluate the model on the test data (e.g., calculate Mean Squared Error)
mse <- mean((test_data$subject_sex - predictions)^2)

cat(mse)
```
